version: "3.8"

services:
  # mysql 数据库. 官方镜像 mysql 8
  mysql-8:
    image: mysql
    # build: msbot-mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - TZ=Asia/Shanghai
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ~/msbot/mysql/data:/var/lib/mysql
      - ~/msbot/mysql/log:/var/log/mysql
      - ./msbot-mysql/init:/docker-entrypoint-initdb.d/
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  
  # go-cqhttp 处理qq交互
  front-end:
    # image: ghcr.io/mrs4s/go-cqhttp:master
    build: ./msbot-go-cqhttp
    restart: on-failure
    env_file: ./.env
    ports:
      - $CQHTTP_LOCAL_PORT:$CQHTTP_DOCKER_PORT
    volumes:
      - ./msbot-go-cqhttp/config.yml:/usr/src/cqhttp/config.yml
      - ./msbot-go-cqhttp/device.json:/usr/src/cqhttp/device.json
      - ./msbot-go-cqhttp/session.token:/usr/src/cqhttp/session.token
      # 文件资源
      - $CQHTTP_LOCAL_DATA_PATH:/usr/src/cqhttp/data

  # java spring-boot 处理业务
  back-end:
    depends_on:
      - mysql-8
    restart: on-failure
    build: ./msbot-java
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
     # 环境变量, 在application.yml中读取
      SERVER_PORT: $SPRING_DOCKER_PORT
      MYSQL_URL: jdbc:mysql://mysql-8:$MYSQLDB_DOCKER_PORT/ms?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PWD: $MYSQLDB_ROOT_PASSWORD
      SQL_LOG: false

    # 常量
      IMAGE_OUT_PUT_FOLDER: /cqhttp.data/images/
      FRONT_END_URL: 'http://front-end:$CQHTTP_DOCKER_PORT'
      BOT_NAME: $BOT_NAME
      BOT_QQ: $BOT_QQ
      MASTER_QQ: $MASTER_QQ
      MANAGER_QQ: $MANAGER_QQ
    volumes:
      - .m2:/root/.m2
      - $CQHTTP_LOCAL_DATA_PATH:/cqhttp.data
    stdin_open: true
    tty: true
